# Generated by Django 5.0.4 on 2024-05-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_userprofile_created_at_userprofile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
    ]
