# Generated by Django 5.0.4 on 2024-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0002_shopcart_amount_shopcart_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='price',
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
